services:
  app:
    build: .
    container_name: screencloud_app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - screencloud_network

  db:
    image: postgres:17.4-bookworm
    container_name: screencloud_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres17_data:/var/lib/postgresql/data
    networks:
      - screencloud_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: screencloud_pgadmin
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - screencloud_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres17_data:
  pgadmin_data:

networks:
  screencloud_network:
    driver: bridge
